# Production overrides - use with: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
services:
  api:
    ports: []  # Don't expose API port directly in production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M

  nginx:
    ports:
      - "80:80"
      # Uncomment if you're handling SSL at the container level (not Cloudflare)
      # - "443:443"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M